### ISSUE TITLE
Bug in v2.10.13

### ISSUE THREAD

**Issue by Dean-Corso** [rowrawer/stream-detector#143] opened 2022-08-23 00:21 UTC
Hi @rowrawer

thanks for new update. I have test it for Firefox & Chrome / Brave and found some issues.

1.) In Brave I use same settings for your extension like I did in the pre version 2.10.12 and I see that the new version does NOT output any infos in the popup window. All empty. Only the counter on the icon works. Just check this again what the problem is. In Firefox it works to show all infos in popup window. No URLs available.

2.) New size infos / MB option. I see the size info are not shown complete anymore the larger the size is. Maybe you did make the site column smaller as before?
Example:
```
214.06 MB
Is shwon now so..
214.06...
```
Not showing the MB at the end  just some dots and in pre version its showing all. Also have a question about the new added size MB limit option I can enable and enter any value. When I have disabled this option (default) then its not showing ANY size info anymore for the files what is WRONG so it should show always the size info (if possible when c-length header present) when the option is disabled. When I have enabled this option (enter 0 for MB value) THEN its working to show all size infos. Normally it should show always the sizes if enabled or not. Just check this too. Could only check this problem in FireFox version only because Brave does not show any URLs as I told under point 1 above. Check and fix it please. Thank you.

**Comment by rowrawer** [comment] 2022-08-23 23:24
Hi, thanks for more feedback.

1. It's unfortunate that it stopped working in Brave. However, I do not plan on providing support for Brave. As far as I know, it works just fine in the latest version of Chrome and Firefox. Have you tried resetting the settings?
2. They display fine for me. Might be an issue with different fonts or display resolutions, but there's not much more I can do about this, as popup windows have a maximum width of only 600px. Try using the new feature of clicking the middle mouse button on the browser icon to open it in a new tab, there might be enough space there. The file size limit option also doesn't seem to impact file size information for me, it works fine regardless of the setting. It bugs out when the amount field is empty, which is something I'll have to fix, but any number works.

**Comment by Dean-Corso** [comment] 2022-08-24 19:31
Hi again,

so you are right! I did reset the lastest version and then it was working. After that I did make same settings as before and it works too. Strange or? Anyway, good to know for next time to use the reset button first in case of any trouble. 😃 

About the display. Not all is shown at the end and just in Firefox version only. Otherwise not so important I think. The middle mouse button, I can open this new tab view but its showing same like in popup what means not all is shown as I told before but somehow I just get this problem in Firefox only. I have test same video grab with Brave browser and there its showing entire info in popup. I also see that in Brave the middle button does nothing only in Firefox it works. Why? Below a image of Firefox...
![FF1_2022-08-24_211947](https://user-images.githubusercontent.com/88513086/186505187-ccc16b1a-eef2-4fc6-8be5-86d59f53bc63.png)
...and here from Brave popup window...
![FF2_2022-08-24_211947](https://user-images.githubusercontent.com/88513086/186505639-b8089de3-5fad-4282-a273-8cb9407169a9.png)
...not sure why Firefox dosen't show the MB unit / info so there is enough space left. Thanks.

**Comment by rowrawer** [comment] 2022-08-24 19:34
Glad to hear it's working better now.

Chrome doesn't support middle mouse button clicks. I understand what you mean with the cut off information, but it fits everything just fine for me. I might try widening that header a little bit just in case.

**Comment by Dean-Corso** [comment] 2022-08-24 21:35
Hi again,

ok I found another problem now with that size limit function you did add. So the scanner of your app will not work anymore when I have the option "Ignore media files smaller than"enabled (entered 0) for custom file extensions. Nothing gets logged and count etc. Only when I disable this option then it works (but not showing any size info only -) = strange. Can you check this out? It only happens in the Chrome version and in Firefox it works normally. I have a example you can check this out...

Example: In your extension enable the "Detect additional file extensions:" option and enter php as extension into and keep the option "Ignore media files smaller than" disabled first. Now call this test php webpage and press the run button...
[Php Testpage](https://www.w3schools.com/php/phptryit.asp?filename=tryphp_datatypes_string)
...now you can see that your extension / AddOn gets triggered in both browser versions. You can see now the URL in popwindow of both called "try_php.php" and only in the Firefox version I can see the size of "305 B" and in the Chrome version I get only a "-" to see = they acting diffrently now (I'am using same settings for both versions). Now go back to your extension / AddOn options and enable the option "Ignore media files smaller than" and enter a 0 into edit field and now press again the run button on the php website. In Firefox you get the same results of URL & size to see but in the Chrome version NOTHING gets triggered anymore = empty = Wrong. I think is must be really a bug now so just test it out and see whether you get same bad results. Thank you.

**Comment by rowrawer** [comment] 2022-08-24 21:47
I can see that it doesn't really work as intended on Chrome. That's too bad, but as stated in the readme, the Chrome version is an unsupported experiment at the end of the day, so please don't expect me to fix bugs that only happen in Chrome. As long as it works in Firefox, I consider it working properly. Of course if anyone else wants to take a look at it and fix it with a pull request, be my guest.

**Comment by Dean-Corso** [comment] 2022-08-24 21:51
So the thing is that its working fine in the pre version 12 without having that extra option size limit. Anyway, I think I will move back to v12 for Chrome. Thanks again.

**Comment by rowrawer** [comment] 2022-08-27 11:16
It might get fixed by accident in future versions, you never know.

**Closed by rowrawer** 2022-08-27 11:16 UTC
