### ISSUE TITLE
No URLs shown in private window mode

### ISSUE THREAD

**Issue by focus64** [rowrawer/stream-detector#91] opened 2021-11-03 18:12 UTC
In private window mode, "No URLs available." is shown when clicking on the "stream detector" icon. Had been working until a few days ago. Not sure if this is intended with recent release updates. If so, please ignore this issue report.

**Comment by rowrawer** [comment] 2021-11-03 22:43
Unfortunately it seems like the current implementation of data storage refuses to work in private mode due to security concerns, according to Firefox. I think it actually works properly on Chrome for once.

**Comment by focus64** [comment] 2021-11-03 22:53
Is it possible to make it work in private mode? At least partially?

**Comment by rowrawer** [comment] 2021-11-03 22:56
No, you'd have to stay on v2.8.3 for the time being. If it doesn't crash and works fine for you then you might as well. I might try doing something about this in the future but I'd probably have to rewrite the storage implementation yet again.

**Comment by focus64** [comment] 2021-11-03 23:05
Good to know. Thanks!

**Comment by goooglefc** [comment] 2021-11-11 22:55
> Unfortunately it seems like the current implementation of data storage refuses to work in private mode due to security concerns, according to Firefox. I think it actually works properly on Chrome for once.

You're right. It works perfectly in Chrome's incognito mode.

**Comment by Mrnofish** [comment] 2021-11-14 03:32
> No, you'd have to stay on v2.8.3 for the time being. If it doesn't crash and works fine for you then you might as well. I might try doing something about this in the future but I'd probably have to rewrite the storage implementation yet again.

In case I haven't missed something: it may be a good idea to convey this particular bit of information front and center, otherwise somebody might simply assume the extension is broken and dump it (assuming that's something you don't completely not care for, ofc).

FWIW I did downgrade to 2.8.3 and it is working fine for the time being, however it does seem to me a non-negligible regression, even though I appreciate the work fixing it would entail, might err on the side of too much and not so very exciting!

Also finding out about the work-around and making sure it sticks, require *just a wee too much* work for the convenience-addled days we live in ^^

**Comment by rowrawer** [comment] 2021-11-14 13:56
> In case I haven't missed something: it may be a good idea to convey this particular bit of information front and center, otherwise somebody might simply assume the extension is broken and dump it (assuming that's something you don't completely not care for, ofc).

I don't particularly care for that - it works just fine for me and I don't use private browsing, and that's all I need. I'll eventually get to it, so there's no need to make a big deal out of it I reckon.

**Comment by Mrnofish** [comment] 2021-11-14 14:49
Fine, however I'll point out that with Firefox being aimed squarely at the privacy-minded, there's a number of users who use Private Mode for their normal browsing (this dispenses from having to regularly clean cookies and storage), and that the extension has only stopped working in Private Mode might not be obvious.

The overall impact might thus be wider than it appears at first sight and might earn the extension some negative feedback.

**Comment by rowrawer** [comment] 2021-11-14 15:01
I get what you're saying, but that's not really something I pay much attention to. I am maintaining this extension primarily for my own personal use anyway. That being said, I'll add a mention to the readme file until it's fixed to hopefully stave off multiple people reporting the same thing.

**Comment by rowrawer** [comment] 2021-12-17 21:07
This should now be fixed in v2.9.0, hopefully.

**Comment by Mrnofish** [comment] 2021-12-18 00:29
That does seem to be the case from some very limited testing.

Thank you so much!

**Comment by Mrnofish** [comment] 2021-12-21 22:54
BTW there's still some weirdness revolving around the Disable Detection checkbox.

It looks like there may be a delay between the switch being flipped and the gears getting in motion, plus I have seen instances of detection happening even though it had been disabled for a while.

**Comment by rowrawer** [comment] 2022-02-14 23:59
Thanks for letting me know. The checkbox shenanigans should now be fixed as of v2.10.0.

**Comment by Mrnofish** [comment] 2022-02-16 05:27
No prob!

Going back to the private window issues in Firefox, the extension appears to be showing streams collected from private windows, inside the list pane of a regular one.

I seem to recall this wasn't the case with previous versions, and I would argue it's an undesirable change, as this appears to require manually clearing the `all tabs` and `previous session` lists manually, whereas the idea behind private mode is *"keep separate / delete stuff as soon as the window is closed"*

I've been hesitant to report this before seeing how it could be part of a workaround for a low-priority issue, tho.

**Comment by rowrawer** [comment] 2022-02-16 11:43
Interesting. I haven't really made any arrangements for private windows before, so it must have been some built-in separation of data storage. I'll look into it.

**Comment by rowrawer** [comment] 2022-02-16 17:54
This should now be working correctly in v2.10.1. I don't use private browsing at all so let me know if there are any quirks.

**Comment by Mrnofish** [comment] 2022-03-21 04:11
Yes it's been working well for a while now. Great job!

There's still a cosmetic issue affecting the icon. If links have been harvested in Private Mode, but none in your regular window, the icon in the latter will show the count for Private Mode instead of 0.

It's no biggie for me, but since you asked about quirks...

**Comment by rowrawer** [comment] 2022-03-21 11:56
Glad to hear it's working.

Yeah, the icon will always show the total. Can't make separate icons per window. I guess it would be possible to recalculate the number every time the user switches between windows, but that doesn't seem to be something worth wasting time on.

**Comment by Mrnofish** [comment] 2022-03-22 05:11
Cool, thank you for clearing that up!

**Closed** 2022-03-22 11:53 UTC
